// resources/js/pages/auth/Login.tsx
import { Form, Link } from '@inertiajs/react';

import { Button } from '@/components/ui/button';
import { Field, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';

type LoginProps = {
    canResetPassword?: boolean;
    canRegister?: boolean;
    status?: string;
};

export default function Login({ canResetPassword, canRegister, status }: LoginProps) {
    return (
        <div className="mx-auto w-full max-w-[400px] px-6 py-10 md:px-0 md:py-16">
            <h1 className="font-display text-[2rem] leading-[2.625rem] font-extrabold tracking-tight text-[var(--auth-ink)]">
                Sign in
            </h1>

            {status ? <p className="text-success mt-4 text-sm">{status}</p> : null}

            <Form action="/login" method="post" className="mt-8">
                {({ errors, processing }) => (
                    <FieldGroup>
                        <Field data-invalid={Boolean(errors.email)}>
                            <FieldLabel htmlFor="email">Email</FieldLabel>
                            <Input id="email" name="email" type="email" autoComplete="email" aria-invalid={Boolean(errors.email)} />
                            {errors.email ? <FieldError>{errors.email}</FieldError> : null}
                        </Field>
                        <Field data-invalid={Boolean(errors.password)}>
                            <FieldLabel htmlFor="password">Password</FieldLabel>
                            <Input
                                id="password"
                                name="password"
                                type="password"
                                autoComplete="current-password"
                                aria-invalid={Boolean(errors.password)}
                            />
                            {errors.password ? <FieldError>{errors.password}</FieldError> : null}
                        </Field>
                        <Button type="submit" className="h-11 w-full rounded-xl" disabled={processing}>
                            Sign in
                        </Button>
                    </FieldGroup>
                )}
            </Form>

            {canResetPassword ? (
                <p className="mt-4 text-center text-sm text-[var(--auth-muted)]">
                    <Link href="/forgot-password" className="text-[var(--auth-link)] hover:underline">
                        Forgot password?
                    </Link>
                </p>
            ) : null}

            {canRegister ? (
                <p className="mt-8 text-center text-[15px] text-[var(--auth-muted)]">
                    No account?{' '}
                    <Link href="/register" className="font-medium text-[var(--auth-link)] hover:underline">
                        Sign up
                    </Link>
                </p>
            ) : null}
        </div>
    );
}

// resources/js/pages/auth/Login.vue
<script setup lang="ts">
import { Form, Link } from '@inertiajs/vue3';

defineProps<{
    canResetPassword?: boolean;
    canRegister?: boolean;
    status?: string;
}>();
</script>

<template>
    <UCard class="w-full max-w-md">
        <template #header>
            <h1 class="text-highlighted text-2xl font-bold tracking-tight">Sign in</h1>
        </template>

        <p v-if="status" class="text-success mb-4 text-sm">{{ status }}</p>

        <Form action="/login" method="post" v-slot="{ errors, processing }" class="flex flex-col gap-4">
            <UFormField label="Email" :error="errors.email">
                <UInput name="email" type="email" autocomplete="email" />
            </UFormField>
            <UFormField label="Password" :error="errors.password">
                <UInput name="password" type="password" autocomplete="current-password" />
            </UFormField>
            <UButton type="submit" block size="lg" :loading="processing">Sign in</UButton>
        </Form>

        <p v-if="canResetPassword" class="text-muted mt-4 text-center text-sm">
            <Link href="/forgot-password" class="text-primary hover:underline">Forgot password?</Link>
        </p>

        <p v-if="canRegister" class="text-muted mt-6 text-center text-sm">
            No account?
            <Link href="/register" class="text-primary font-medium hover:underline">Sign up</Link>
        </p>
    </UCard>
</template>
